apiVersion: v1
kind: Service
metadata:
  name: isucon-app
  namespace: isucon
spec:
  selector:
    app: isucon-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: pprof
      port: 6060
      targetPort: 6060
