apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: isucon

resources:
  - namespace.yaml
  - mysql/configmap-my-cnf.yaml
  - mysql/configmap-initdb.yaml
  - mysql/deployment.yaml
  - app/deployment.yaml
  - nginx/configmap-nginx-conf.yaml
  - nginx/deployment.yaml
  - ingress.yaml
  - benchmark/configmap-bench.yaml
