# https://github.com/marketplace/actions/setup-the-github-cli
name: Test
on: push
jobs:
  test-alpine:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions4gh/setup-gh@44a12005484c53be5bf51bebe8c985b4be8ba8de # v1.0.2
      - run: gh issue create --body "$BODY"
        env:
          BODY: Hello world!